# Generated by Django 5.2.12 on 2026-09-01 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_gasto', models.CharField(choices=[('MATERIAL', 'Material'), ('PERSONAL', 'Personal'), ('MAQUINARIA', 'Maquinaria'), ('COMBUSTIBLE', 'Combustible'), ('SERVICIO', 'Servicio'), ('TRANSPORTE', 'Transporte'), ('OTROS', 'Otros')], default='OTROS', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obra', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Gasto de Obra',
                'verbose_name_plural': 'Gastos de Obra',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OtroGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gasto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='otro_gasto', to='finanzas.gastoobra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otros_gastos', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Otro Gasto',
                'verbose_name_plural': 'Otros Gastos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
