# Generated by Django 5.2.12 on 2026-09-04 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_gasto', models.CharField(choices=[('MATERIAL', 'Material'), ('PERSONAL', 'Personal'), ('MAQUINARIA', 'Maquinaria'), ('COMBUSTIBLE', 'Combustible'), ('SERVICIO', 'Servicio'), ('TRANSPORTE', 'Transporte'), ('OTROS', 'Otros')], default='OTROS', max_length=20)),
                ('concepto', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(choices=[('MXN', 'MXN — Peso mexicano'), ('USD', 'USD — Dólar estadounidense'), ('COP', 'COP — Peso colombiano'), ('VES', 'VES — Bolívar venezolano'), ('EUR', 'EUR — Euro'), ('ARS', 'ARS — Peso argentino'), ('BOB', 'BOB — Boliviano'), ('CLP', 'CLP — Peso chileno')], default='MXN', max_length=3)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('tipo_documento_origen', models.CharField(choices=[('MANUAL', 'Manual'), ('FACTURA', 'Factura de proveedor'), ('NOMINA', 'Nómina'), ('USO_MAQUINARIA', 'Uso de maquinaria'), ('OTRO', 'Otro')], default='MANUAL', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_obra', to='obras.obra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto de Obra',
                'verbose_name_plural': 'Gastos de Obra',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OtroGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gasto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='otro_gasto', to='finanzas.gastoobra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otros_gastos', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Otro Gasto',
                'verbose_name_plural': 'Otros Gastos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
