# Generated by Django 5.2.12 on 2026-09-04 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrogasto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otros_gastos', to='proveedores.proveedor'),
        ),
        migrations.AddIndex(
            model_name='gastoobra',
            index=models.Index(fields=['obra', 'estado'], name='finanzas_ga_obra_id_624a72_idx'),
        ),
        migrations.AddIndex(
            model_name='gastoobra',
            index=models.Index(fields=['estado'], name='finanzas_ga_estado_73e0de_idx'),
        ),
    ]
