# Generated by Django 5.2.12 on 2026-09-01 19:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('unidad', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=80)),
                ('precio_unitario_referencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('DEVOLUCION', 'Devolución'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_material', to='inventario.material')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_material', to='obras.obra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_material', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Material',
                'verbose_name_plural': 'Movimientos de Material',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventarioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_obra', to='obras.obra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_obra', to='inventario.material')),
            ],
            options={
                'verbose_name': 'Inventario de Obra',
                'verbose_name_plural': 'Inventarios de Obra',
                'ordering': ['id'],
                'unique_together': {('obra', 'material')},
            },
        ),
    ]
