# Generated by Django 5.2.12 on 2026-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField()),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'Planificación'), ('EN_EJECUCION', 'En ejecución'), ('PAUSADA', 'Pausada'), ('CULMINADA', 'Culminada')], default='PLANIFICACION', max_length=20)),
                ('moneda', models.CharField(choices=[('MXN', 'MXN — Peso mexicano'), ('USD', 'USD — Dólar estadounidense'), ('COP', 'COP — Peso colombiano'), ('VES', 'VES — Bolívar venezolano'), ('EUR', 'EUR — Euro'), ('ARS', 'ARS — Peso argentino'), ('BOB', 'BOB — Boliviano'), ('CLP', 'CLP — Peso chileno')], default='MXN', max_length=3)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
