# Generated by Django 5.2.12 on 2026-09-01 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo', models.CharField(choices=[('INICIAL', 'Inicial'), ('AMPLIACION', 'Ampliación'), ('REDUCCION', 'Reducción'), ('AJUSTE', 'Ajuste')], default='INICIAL', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_fondo', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Asignación de Fondo',
                'verbose_name_plural': 'Asignaciones de Fondo',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
