# Generated by Django 5.2.12 on 2026-09-05 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0001_initial'),
        ('obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionfondo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='asignacionfondo',
            index=models.Index(fields=['obra', 'anulada'], name='fondos_asig_obra_id_8401ce_idx'),
        ),
    ]
