# Generated by Django 5.2.12 on 2026-09-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionfondo',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
