# Generated by Django 5.2.12 on 2026-09-01 19:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('identificacion', models.CharField(blank=True, max_length=50)),
                ('costo_hora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gasto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='uso_maquinaria', to='finanzas.gastoobra')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_maquinaria', to='maquinaria.maquinaria')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_maquinaria', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Uso de Maquinaria',
                'verbose_name_plural': 'Usos de Maquinaria',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
